= ScalaSignal - Signal Processing Library for Scala =

== Introduction ==

ScalaSignal is a fledgling signal processing library for the Scala
language, with the eventual aim of implementing much of the functionality 
found in other signal processing toolboxen.

ScalaSignal is released under the LGPL.  See LICENSE for details.
Copyright (C) Jonathan Merritt 2011.

== Current Functionality ==

ScalaSignal currently implements the following:

  - `filter(b, a, x, si)` - digital filtering with FIR or IIR filters
  - `filtfilt(b, a, x)` - forward-reverse zero phase lag digital filtering

== Installation ==

Check out the project from GitHub (this command uses the Read-Only
repository:

  $ git clone git://github.com/lancelet/scalasignal.git

This will create a new directory called `scalasignal`.  Next, use
http://code.google.com/p/simple-build-tool/[sbt] to compile the project:

  $ cd scalasignal
  $ sbt

http://code.google.com/p/simple-build-tool/[sbt] will launch, and collect
everything it needs for the project.  Within `sbt`, you can then run:

  > update
  > test

This will run the packaged unit tests for the project.