= ScalaSignal - Signal Processing Library for Scala =

== Introduction ==

ScalaSignal is a fledgling signal processing library for the Scala
language, with the eventual aim of implementing much of the functionality 
found in other signal processing toolboxen.

ScalaSignal is released under the LGPL.  See LICENSE for details.
Copyright (C) Jonathan Merritt 2011.

== Current Functionality ==

ScalaSignal currently implements the following:

  - `bandwidth(pd, fract)` - Signal bandwidth estimation
  - `butterSOSEven(n, Wn)` - SOS coefficients for even-order Butterworth 
     filters
  - `detrend(x)` - Removes a linear trend from a signal
  - `filter(b, a, x, si)` - digital filtering with FIR or IIR filters
  - `filtfilt(b, a, x)` - forward-reverse zero phase lag digital filtering
  - `fft(x)` - Fast Fourier Transform
  - `ifft(h)` - Inverse Fast Fourier Transform
  - `psd(x, fs)` - Power spectral density estimation     
  - `sosfilt(sos, x)` - second order section (SOS) / biquad filtering
  - Windowing functions:
    ** `hann(n, periodic)` - Hann (Hanning / raised cosine) window
    ** `rectwin(n)` - rectangular (identity) window
    ** `tukeywin(n, a)` - Tukey (tapered cosine) window

== Installation ==

Check out the project from GitHub (this command uses the Read-Only
repository):

  $ git clone git://github.com/lancelet/scalasignal.git

This will create a new directory called `scalasignal`.  Next, use
https://github.com/harrah/xsbt[sbt/xsbt] to compile the project:

  $ cd scalasignal
  $ sbt

https://github.com/harrah/xsbt[sbt/xsbt] will launch, and collect
everything it needs for the project.  Within `sbt`, you can then run:

  > test

This will run the packaged unit tests for the project.

== NOTE: Problems with netlib-java-0.9.3.pom ==

If you encounter sha1 hash conflicts when fetching `netlib-java-0.9.0.pom` from
repo.scalanlp.org, a workaround is to checkout
https://github.com/scalala/Scalala[Scalala] from GitHub, and then run

  $ sbt update
 
It will then pull `netlib-java` into the Ivy cache, and sbt/xsbt will happily
use the cache version.